version: "3.8"
services:
  db:
    image: mariadb
    volumes:
      - ./SQL:/docker-entrypoint-initdb.d
    environment:
      MYSQL_RANDOM_ROOT_PASSWORD: "yes"
      MYSQL_DATABASE: node
      MYSQL_USER: node
      MYSQL_PASSWORD: node
  web:
    build: .
    command: node src/main.js
    ports:
      - "8080:8080"
    depends_on:
      - db
