services:
  db:
    image: mariadb
    volumes:
      - ./SQL:/docker-entrypoint-initdb.d
    environment:
      MYSQL_RANDOM_ROOT_PASSWORD: "yes"
      MYSQL_DATABASE: node
      MYSQL_USER: node
      MYSQL_PASSWORD: node
  back:
    build: .
    command: node src/main.js
    ports:
      - "${API_PORT}:${API_PORT}"
    depends_on:
      - db
  front:
    build: ./front
    ports:
      - "80:80"
    depends_on:
      - back

