services:
  db:
    image: mariadb
    volumes:
      - ./db:/docker-entrypoint-initdb.d
    environment:
      MYSQL_RANDOM_ROOT_PASSWORD: "yes"
      MYSQL_DATABASE: node
      MYSQL_USER: node
      MYSQL_PASSWORD: node
  back:
    build: ./back
    command: npm start
    ports:
      - "8080:8080"
    depends_on:
      - db
  front:
    build: ./front
    ports:
      - "80:80"
    depends_on:
      - back

